# Generated by Django 4.2.6 on 2024-02-13 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Stname',
            new_name='stname',
        ),
    ]
